### ISSUE TITLE
Nested test generation

### ISSUE THREAD

**Issue by chaunceyau** [nestjs/nest-cli#1023]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Running `nest generate controller/service/etc someName` generates files `someName.__.ts and someName.__.test.ts` in the `someName directory`. Currently you must generate and then drag to new folder and update imports (if IDE doesn't automatically fix for you)

## Expected behavior

An optional config variable `e.g. useFolderForTests` in `nest-cli.json or -- command option` allowing generated test to be added to the `someName/__tests__/ directory`

## What is the motivation / use case for changing the behavior?

Common behavior/pattern to structure tests in folder.

If someone can point me in the right direction, I don't mind submitting a PR. I understand the configuration loading part of codebase, but not understanding which lines are actually generating the config files

**Comment by jmcdo29** [comment]
The files are actually being generated via the [nestjs/schematics](https://github.com/nestjs/schematics). You'd need to figure out a way to determine which configuration of schematic should be followed. 

Is this something Angular does? Wondering if we can view their code and see if there's something similar to work off of.

**Comment by kamilmysliwiec** [comment]
This is a recommended convention for NestJS apps (and it's inherited from Angular) to put unit test spec files in the same folder as the application source code files that they test because:
- Such tests are easy to find.
- You see at a glance if a part of your application lacks tests.
- Nearby tests can reveal how a part works in context.
- When you move the source (inevitable), you remember to move the test.
- When you rename the source file (inevitable), you remember to rename the test file.

https://angular.io/guide/testing#place-your-spec-file-next-to-the-file-it-tests

There are currently no plans to change it.
