### ISSUE TITLE
Generate gRPC controller from .proto files

### ISSUE THREAD

**Issue by ThomRick** [nestjs/nest-cli#136]
AS a user I WANT TO generate gRPC controllers from .proto files WHEN I generate controller
   - use ```nest g grpc-controller name --file [file-path]```

**Comment by Sy-D** [comment]
I was looking if someone already requested to enhance the `nest g resource` command for microservices by being able to choose grpc instead of being limited to message pattern based services. Therefore, i came across this feature request which comes pretty close if not might be even better and would like to know what happened to this.
