### ISSUE TITLE
nest new crashes when installing dependencies

### ISSUE THREAD

**Issue by Raqbit** [nestjs/nest-cli#138]
This happens when picking either npm or yarn.

As I would think this is a system dependent issue, here are some details:

Nestjs-cli version: `5.1.2` installed via yarn.
Node version: `v8.11.2` installed via NVM.
NPM version: `v5.6.0` installed via NVM.
Yarn version: `v1.6.0` installed as package via NPM.

OS: Ubuntu 18.04, linux

Simply running `nest new [name]` and hitting enter for all the questions triggers this crash.

```
? Which package manager would you ❤️  to use? yarn
▹▹▹▹▹ Take ☕️  or 🍺  during the packages installation process and enjoy your timeevents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/sh ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by VinceOPS** [comment]
I assume this is somehow related to [this](https://github.com/nodejs/node/issues/9644), and the culprit is [this line](https://github.com/nestjs/nest-cli/blob/master/lib/package-managers/abstract.package-manager.ts#L31). I was able to reproduce it removing the newly-created folder before this line is executed.

However, I have no clue why the project folder would not exist. I'm running Debian 9 here and I didn't experience this issue.

**Comment by josiahdahl** [comment]
@Raqbit What was the project name you were trying to generate (or something similar)?

@ThomRick I think you were right about the above mentioned issue with non kebab-case naming.

`nest new test` and `nest new test-two` works

`nest new testTwo` fails because it creates the directory `test-two` but expects the directory to be `testTwo`, which would explain the directory not being created.

![image](https://user-images.githubusercontent.com/5520415/40933953-0599b0da-67e8-11e8-85de-1c9f233ffd0f.png)

**Comment by ThomRick** [comment]
No links between simple / kebab / camel case app name and the error.
The cli transforms the app name to be always in kebab case before calling the nest schematic collection.
You can type ```app name``` / ```app-name``` / ```App Name``` / ```appName``` / ```AppName``` the result will always be ```app-name```.

**Comment by josiahdahl** [comment]
@ThomRick I did some debugging and the non-dasherized directory/project name was being passed to the `install` method in `new.action.ts` (see right after the package manager selection).

A fix is here https://github.com/nestjs/nest-cli/pull/151

![image](https://user-images.githubusercontent.com/5520415/40939564-ed9d1ce4-67f9-11e8-946a-983f223a3658.png)

**Comment by Raqbit** [comment]
@josiahdahl Yes, I can confirm that the project was probably `NestTest`.
