### ISSUE TITLE
Nest create a subfolder inside subfolder when working with monorepo

### ISSUE THREAD

**Issue by felinto-dev** [nestjs/nest-cli#1425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I executed the follow command:

`npx nest build hotmart
`
![image](https://user-images.githubusercontent.com/32253743/143482099-e1775955-8da9-48f6-8380-1c7c84ae7b63.png)

NestJS places the "hotmart" folder inside the "hotmart" directory.

### Minimum reproduction code

https://github.com/felinto-dev/repro-nest-monorepo-issue

### Steps to reproduce

```
git clone https://github.com/felinto-dev/repro-nest-monorepo-issue
yarn
npx nest build hotmart
```

check the "dist" folder

### Expected behavior

It should follow the following structure:

dist
-- apps
---- hotmart
---- hotjoin-bot

### Package version

8.1.5

### NestJS version

8.2.3

### Node.js version

14.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
You're using the tsc compiler instead of webpack, which tries to preserve the directory structure when there are multiple root directories (i.e. you're importing a ts file from outside of `src/` or its equivalent).  As you're importing from the bot directory from inside your main server, this is the expected functionality. You can swap over to using webpack and get a single output file per build, or you can not import from outside the application root
