### ISSUE TITLE
Cannot generate a project named using numbers

### ISSUE THREAD

**Issue by ahmadalfy** [nestjs/nest-cli#1519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Try creating a new project with a number:

```
nest new 360
```

It throws the following error:

```
Error: Schematic input does not validate against the Schema: {"name":360,"directory":"undefined","skip-git":false,"strict":false,"package-manager":"undefined","language":"ts","collection":"@nestjs/schematics"}
Errors:

  Data path "/name" must be string.

Failed to execute command: node @nestjs/schematics:application --name=360 --directory=undefined --no-dry-run --no-skip-git --no-strict --package-manager=undefined --language="ts" --collection="@nestjs/schematics"
```

### Minimum reproduction code

Not needed

### Steps to reproduce

1. Install the CLI
2. Create a new project with a name consisting of number
3. The error will show up

### Expected behavior

A project name that uses a number should be treated as a string and it should create the folder as expected

### Package version

8.2.0

### NestJS version

8.2.0

### Node.js version

14.17.6

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
looks like this is due to how `@angular-devkit/schematics` works

Here:

https://github.com/nestjs/schematics/blob/c6ba5535a8857412de1de64b31a4de30b8bbc2d0/src/lib/application/schema.json#L7-L8

`name` is defined as a `string`, and that lib coerces the app name to `number` when you supply some valid number (before any nestjs code) and then try to validate against that expected type.

**Comment by Tony133** [comment]
Since the PR referring to this issue has been merged, I think this issue can be closed, right?

**Comment by ahmadalfy** [comment]
Closing this
