### ISSUE TITLE
Inconsistent status codes returned on errors from nest build

### ISSUE THREAD

**Issue by schmoesta** [nestjs/nest-cli#1564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In some cases the `nest build` command will still exit with code 0, even if it encountered an error.

Possibly related: #423, #1044

### Minimum reproduction code

https://github.com/nestjs/typescript-starter

### Steps to reproduce

1. `npm i`
2. `rm tsconfig.build.json`
3. `npx nest build; echo $?`

This will result in:
```
 Error  Could not find TypeScript configuration file "tsconfig.build.json". Please, ensure that you are running this command in the appropriate directory (inside Nest workspace).

0
```

On the other hand:
1. `npm i`
2. `rm src/app.module.ts`
3. `npx nest build; echo $?`

results in:
```
src/main.ts:2:27 - error TS2307: Cannot find module './app.module' or its corresponding type declarations.

2 import { AppModule } from './app.module';
                            ~~~~~~~~~~~~~~

Found 1 error(s).

1
```

### Expected behavior

The command should exit with code 1 if there's an error.

### Package version

8.2.2

### NestJS version

8.3.1

### Node.js version

v16.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I'm not sure about the underlying mechanics here, but I noticed that there are some other cases where the status code is inconsistent:

```
$ npx nest foo; echo $?

 Error  Invalid command: foo
See --help for a list of available commands.

1

$ npx nest g foo; echo $?
Invalid schematic "foo". Please, ensure that "foo" exists in this collection.
0
```

**Comment by stanimirovv** [comment]
Interesting issue. I couldn't reproduce it on ubuntu with bash.

For the "Other" section how many times do you need to run the command to simulate the error ?

**Comment by micalevisk** [comment]
this happens because here:

https://github.com/nestjs/nest-cli/blob/6ce99a06152a12c9eeb483aaae3889fe0d48c327/lib/compiler/helpers/tsconfig-provider.ts#L13

the exit code isn't changed.

Nor here:

https://github.com/nestjs/nest-cli/blob/d7717c9bd69cc5885374e7337fd7eb13008e1701/actions/build.action.ts#L59-L65

**Comment by schmoesta** [comment]
> Interesting issue. I couldn't reproduce it on ubuntu with bash.
> 
> For the "Other" section how many times do you need to run the command to simulate the error ?

Apologies, @stanimirovv. I made a mistake copying over the commands from my terminal. `nest foo` returns with 1, `nest g foo` returns with 0. Have corrected it in the issue description now.

**Comment by stanimirovv** [comment]
@micalevisk I've made a PR that adresses these issues for another part of the code where there was an issue with `system.exit`: https://github.com/nestjs/nest-cli/pull/1566
With these changes all system.exit's are correct.

Since there are quite a few places where an error is thrown and some places where an error needs to be thrown maybe it makes sense to add a top level try/catch in the bootstrap function. What do you think ?

**Comment by micalevisk** [comment]
@stanimirovv I'm not aware of the whole flow but having one try/catch that will call the `process.exit(1)` sounds better than having few try/catch with this logic

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/1566
