### ISSUE TITLE
Allow passing arguments to `nest start <app>`

### ISSUE THREAD

**Issue by alko89** [nestjs/nest-cli#1844]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We have a nest monorepo project. I've recently created a cli app to help with debugging and testing. Using  `nest start <app>` doesn't allow passing additional arguments to the monorepo CLI app.

### Describe the solution you'd like

Enable passing optional arguments to Nest app using Nest CLI.

### What is the motivation / use case for changing the behavior?

Enables more usecases and flexibility to the CLI.

**Comment by alko89** [comment]
Sure, I can look into it :+1:

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/1847

**Comment by zackdotcomputer** [comment]
This issue was not resolved by the above PR, apparently, because commands like `yarn nest start sync -- --syncType=employees` still fail with the error `error: unknown option '--syncType'`. I assume from reading the start.command file that this is because commander is not being called with `allowUnknownOption` enabled. I will try to make a PR to enable that.
