### ISSUE TITLE
@nestjs/schematics dependency introduce breaking changes in minor version

### ISSUE THREAD

**Issue by almogyehuda** [nestjs/nest-cli#1899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This is not related specific to @nestjs/schematics package, but because this package dependent on it.

Using nestjs-cli with the latest version, the package.json declares it needs minimum "node": ">= 12.9.0".

This nestjs-cli tool dependent on @nestjs/schematics with caret ("@nestjs/schematics": "^9.0.0")
With that, when @nestjs/schematics released new patch version with update to @angular-devkit/schematics@15.0.4
requires now node version "^14.20.0 || ^16.13.0 || >=18.10.0".
https://github.com/nestjs/nest-cli/blame/e28854e781ff43eb9a731751b75fdd3dca4cfc87/package.json#L44

This breaks the dependency on lower node version.

If you may release a fix, because currently @nestjs/cli declares "node": ">= 12.9.0" - but it's not anymore.

### Minimum reproduction code

https://github.com/nestjs/nest-cli

### Steps to reproduce

1. create npm project with node.js version 14.16.1
2. install @nestjs/cli version 9.1.5 (for example)

### Expected behavior

versioning should honor package.json declaration on engine dependency  

### Package version

9.1.5

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by Tony133** [comment]
With the node `v14.20.0` as the "minimum" version, you should be able to resolve the error.

However, perhaps we should change the engine to `>=14.20.0` since it is also an LTS version, but I don't know is it possible to do that now, we should also update the documentation. 
Maybe with the next major version of NestJS ? 🤔

**Comment by micalevisk** [comment]
a hot fix to this would be: remove the `engines.node` entry from `@nestjs/cli` (if we cannot downgrade `@angular-devkit/schematics` to v14)

---

:up: on drop suppor for node12 in nestjs v10

**Comment by Tony133** [comment]
Doing the downgranding of `@angular-devkit/schematics` I don't think it makes much sense. Removing the `engines.node` I don't even know because if I remember correctly it was added when v9 of NestJS was released because it was giving errors with lesser versions of Node. In any case the problem can be solved by changing the version of the node installed on the machine, so it is not "blocking" at the moment.
Then given the previous compatibility change of node from version 10.x to 12.x, I can imagine that it will be done in the next major version of NestJS. 🚀 😄

Just that v14.x and v16.x of nodejs are about to end their life already this year, maybe putting v18 maybe is a gamble? 😄
As soon as he finds some time, let's see what Kamil thinks.

**Comment by micalevisk** [comment]
my only concern is that this constraint seems to be related with dev deps only

So if we can build a nestjs app without `@nestjs/cli` (and its feature) then enforcing node12 even in v10 just due to some dev dep on `@nestjs/cli` doesn't seems to be good decision to me... The good part on this is that we can start using node14 features in v10.

but yeah, it's 2023, people must avoid nodejs 12.

**Comment by kamilmysliwiec** [comment]
Agree with @micalevisk. To fix this issue, you can either to what suggested above, or downgrade to the older version of @nestjs/schematics
