### ISSUE TITLE
Please turn on `strictNullChecks` option to be `true`

### ISSUE THREAD

**Issue by samchon** [nestjs/nest-cli#2057]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

TypeScript has supported strict options since very long time ago. Maybe 8 years in my memory.

By the way, NestJS is still configuring `strict` option to be `false`. I think the `strict` option is the most powerful feature of  TypeScript. Many TypeScrpt lovers say that, "If the `strict` option is not supported, I may choose Kotlin or other famous languages instead." I totally agree with their insights, but unfortunately, NestJS is guiding users to turn off the `strict` option.

Whenever runnnig `nest new` command of `@nestjs/cli`, it configures `tsconfig.json` to turn off that `strict` option.

### Describe the solution you'd like

Hope `@nestjs/cli` to configure `strict` option to be `true`

### Teachability, documentation, adoption, migration strategy

I know that if turn on the `strictNullChecks` option, `class-validator` and `@nestjs/swagger` can't distinguish nullable or undefindable atomic types. They judge those nullable number or undefindable string type as an object type. In such reason, when defining a DTO with `strict` option, users must call additonal decorator functions like `@IsNumber()` or `@IsString()`.

```typescript
export SomeDto {
    @IsString()
    @IsOptional()
    @ApiProperty({
        type: "string",
        nullable: true,
        minLength: 5,
        maxLength: 100,
        description: "Title of the article.",
    })
    title!: string | null;
}
```

However, turning off `strict` option just for avoiding lack of dependency libraries, I think it seems crazy.

I think the NestJS team should explore alternatives and find a solution. I think it's just crazy to close your eyes and turn your head away from an existing problem because it's difficult.

### What is the motivation / use case for changing the behavior?

Let's take advantages of `strict` option, that most of TypeScript lovers want.

**Comment by hjhjdev** [comment]
+1

**Comment by Papooch** [comment]
When we first started with Nest and Typescript in our company long time ago, this really bit us in the butt very late in the project when a lot of "`cannot read 'x' of undefined`" errors started to pop out on various places, even though it typechecked correctly. We did not know this setting even existed, but when we turned it on, red squiggles appeared _everywehre_.

Had we known about it, or had it been enabled by default, there'd be a lot more safety in the project from the start.

I would suggest adding it as a feature flag to `nest new`, with `true` being the default since `v10`.

**Comment by micalevisk** [comment]
yeah, we need that in v10 for sure! Here's a good article on how to migrate the codebase to `strictNullChecks` mode: [Inside Figma: a case study on strict null checks](https://www.figma.com/blog/inside-figma-a-case-study-on-strict-null-checks/)

---

We just need to update the following line from `@nestjs/schematics`: https://github.com/nestjs/schematics/blob/a5f1300ce4cb7eb1b196b4968f28a8a10a2c9a46/src/lib/application/files/ts/tsconfig.json#L15 (and in the [TS starter repo](https://github.com/nestjs/typescript-starter/blob/master/tsconfig.json) as well)

I got only one concern tho: the `--strict` flag of nestjs CLI turns on few others strict flags of tsc compiler that might not be good to have enabled by default (to folks that are not familiar with TS), so that CLI option should still be `false` by default.

**Comment by Papooch** [comment]
> the --strict flag of nestjs CLI turns on few others strict flags of tsc compiler that might not be good to have enabled by default

```
    "strictNullChecks": <%= strict %>,
    "noImplicitAny": <%= strict %>,
    "strictBindCallApply": <%= strict %>,
    "forceConsistentCasingInFileNames": <%= strict %>,
    "noFallthroughCasesInSwitch": <%= strict %>
```

Hm, I would argue that these settings are useful for any project that is starting out with typescript. Also NestJS is an opinionated framework, and in my opinion, all of these are _great_ to have enabled when starting a _new_ NestJS project. Apart from the consistent naming one, they prevent shooting yourself in the foot.

**Comment by samchon** [comment]
Well, is NestJS team is also considering just `strict` option?

**Comment by micalevisk** [comment]
I think that the tsc `strict` option is too much to be a default for nestjs apps. I'm pretty sure that we will got a bunch of typescript-related questions just because of that. That's why the the `--strict` flag just enable few ones.

---

@Papooch To me, the `noImplicitAny` is too opinative to have as a default. People would struggle on migrating their js apps to ts due to that, I guess.

**Comment by Papooch** [comment]
> People would struggle on migrating their js apps to ts due to that, I guess

They can always run it with strict set to falsey if they intend on _migrating_ from a JS project.

The whole point of defaults is that they should be reasonable for the majority of use cases. And I doubt that the majority of NestJS projects are started in order to migrate an old solution.

Also, when you're migrating an app to a new technology, you usually do some deeper research about compatibility with the old technology.

Not so much when starting a new project, then you just want to get the default experience. And I guess we should strive for making the default experience as pleasant and _typesafe_ as possible.

**Comment by minhtaile2712** [comment]
Then this hint in [the documentation](https://docs.nestjs.com/first-steps#setup) is not correct:

"To create a new project with TypeScript's [strict](https://www.typescriptlang.org/tsconfig#strict) mode enabled, pass the `--strict` flag to the `nest new` command."

Because it only toggles some options (5 to be exact). **It did not use TypeScript's `strict` option**.

This kind of misleading information should not exist. It should say something like this:

"To create a TypeScript project with stricter features set, pass the `--strict` flag to the `nest new` command."

Then this flag should be named `--stricter` or `--more-strict` instead.

**Comment by kamilmysliwiec** [comment]
> This kind of misleading information should not exist. It should say something like this:

@minhtaile2712 Would you like to create a PR for this?

> Let's take advantages of strict option, that most of TypeScript lovers want.

Turning the strict mode on boils down to opening 1 file and changing a single line of code, so if there's someone already familiar with this option (who wants/loves to use it) then it should be a pretty straightforward change.

> There's a tough balance with an opinionated framework on determining when to turn on a setting like strict mode and when to leave it opt in for the sake of those learning Typescript and Nest at the same time, but I think making people aware of the option would make it a better experience, and then those who really want it are able to opt in to it and/or make an alias so that nest new on their terminal does it by default

Agree

> Not so much when starting a new project, then you just want to get the default experience. And I guess we should strive for making the default experience as pleasant and typesafe as possible.

While I agree that making things as typesafe as possible is generally preferable, we have to keep in mind that setting `strictNullChecks`/`noImplictAny` to true makes the learning curve steeper, which means that the default experience is not going to be "more pleasant" for all framework users. Seeking for the right balance is always hard so oftentimes it's just one or another - stricter but more difficult to grasp, or less strict at first so you can adapt & reiterate later on (+ those that are already comfortable with this setting & proficient with the language can turn this on right away). Each of those has its pros and cons, but frankly, I don't see any major advantages of one over the other (approach). I prefer the strict mode myself, but I've seen teams that rather lean towards some of the strict options turned off at first, for simplicity's sake.

Luckily this doesn't seem to be a pressing issue. If someone wants to use this option, then one can just turn it on. Currently, there are no plans to make it _the default_ but it may change over time
