### ISSUE TITLE
Generate options has no effect when executing nest generate in a subfolder

### ISSUE THREAD

**Issue by suiyun39** [nestjs/nest-cli#2685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In `nest-cli.json`, add `generateOptions.spec: false`. Then, in a subfolder run `nest generate controller`, cli still generates spec files.

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-gt4dly

### Steps to reproduce

1. `cd ./src`
2. `nest generator controller user`

### Expected behavior

The Nest CLI should respect nest-cli.json, just like the Angular CLI does.

### Package version

10.4.2

### NestJS version

10.3.10

### Node.js version

22.5.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
You should always run NestJS CLI commands from the root directory of the project so it can locate your `nest-cli.json` file - otherwise, it would have to go N levels up (and it's hard to determine when to stop). If you want to generate a module in a specific directory, just run `nest g co random-folder/my-module`
