### ISSUE TITLE
Can't generate controller when I installed nest-cli locally as devDependency

### ISSUE THREAD

**Issue by msmadja** [nestjs/nest-cli#323]
I can't generate controller and got this error: 
Failed to execute command: "/Users/XX/Documents/api-test/node_modules/@nestjs/cli/node_modules/.bin/schematics" @nestjs/schematics:controller --name=product --no-dry-run --spec --collection="@nestjs/schematics" --language="ts" --sourceRoot="src"

When I tried to install locally the npm install  @nestjs/cli --save-dev

I used this command:
npx nest g controller product

**Comment by kamilmysliwiec** [comment]
Duplicate of https://github.com/nestjs/nest-cli/issues/145

**Comment by kjbetz** [comment]
I don't believe this is a duplicate. I too am having this issue. In the duplicate it says this was fixed with a pull request, yet the issue seems to still be happening.

`npx nest g co items`

`'"C:\Users\kjbet\Source\Repos\kjbetz\nest-rest-api\node_modules\@nestjs\cli\node_modules\.bin\schematics"' is not recognized as an internal or external command,
operable program or batch file.

Failed to execute command: "C:\Users\XX\Source\Repos\XX\nest-rest-api\node_modules\@nestjs\cli\node_modules\.bin\schematics" @nestjs/schematics:controller --name=items --no-dry-run --spec --collection="@nestjs/schematics" --language="ts" --sourceRoot="src"`

**Comment by carlosHolaPartner** [comment]
hi, i have the same issue
Failed to execute command: "D:\Youtube\xx\Nestjs\nestjs-products-api\node_modules\.bin\schematics" @nestjs/schematics:module --name=producto --no-dry-run --collection="@nestjs/schematics" --language="ts" --sourceRoot="src" --spec

**Comment by SaulGreen** [comment]
I have the same issue:

Failed to execute command: "/Users/xx/Documents/Development/Nest/blog-backend-node/node_modules/.bin/schematics" @nestjs/schematics:controller --name=blog --no-dry-run --collection="@nestjs/schematics" --language="ts" --sourceRoot="src" --spec

I've tried every solution i've found, update ts, manually install dependency, but nothing seems to be working. Do you guys found anything?

**Comment by JA21** [comment]
Muchachos yo lo solucione instalando todo con el npm, creo que el yarn es el que genera problemas.

**Comment by marcusp619** [comment]
Having same issue as @SaulGreen

**Comment by micalevisk** [comment]
@marcusp619 for which command?

**Comment by marcusp619** [comment]
> Failed to execute command: "/Users/xx/Documents/Development/Nest/blog-backend-node/node_modules/.bin/schematics" @nestjs/schematics:controller --name=blog --no-dry-run --collection="@nestjs/schematics" --language="ts" --sourceRoot="src" --spec
> 
> I've tried every solution i've found, update ts, manually install dependency, but nothing seems to be working. Do you guys found anything?

```nest g mo```
