### ISSUE TITLE
Build issue with library and project

### ISSUE THREAD

**Issue by ruslanguns** [nestjs/nest-cli#333]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Default nestjs project when you build it creates a simple structure dist in your root folder:
```
├───dist
│   ├───modules
│   └───shared
```

But if you add a library from schematics and in build it have different behaviour
```
├───dist
│   ├───libs
│   └───src
│       ├───auth
│       └───shared
```
So nodemon does not work properly since it by default look at dist not at dist/src.

## Minimal reproduction of the problem with instructions

* Create a hello world project in nestjs
* Add from schematics a new library with any prefix
* Try start:dev or prod (it wont start properly, only will built the dist folder.)

## Environment

```
OS: Windows
Nestjs Version 6.5.0
Node Version: v12.3.1
NPM Version: 6.10.0
```

**Comment by kamilmysliwiec** [comment]
Yes, you have to update your configuration manually. Library feature is still not fully covered

**Comment by ruslanguns** [comment]
What settings do you recommend?

**Comment by ruslanguns** [comment]
I updated the node_modules and it is working as expected 
![image](https://user-images.githubusercontent.com/19806968/61253060-a2fd1880-a757-11e9-9ecc-2c6d7587ceaa.png)


I am closing this issue, maybe you already fixed it.

**Comment by ruslanguns** [comment]
I am reopening the issue. Since it's happening again. I am providing a sample repo for easy to go reproduction:  https://github.com/ruslanguns/nestjs-test-repo

Comands `yarn start:prod`, `yarn build`, `yarn start:dev` are not working, since the tsconfig is wrong with the schematics (my guess).

**Comment by ruslanguns** [comment]
@jmcdo29 provided a work around in a PR https://github.com/ruslanguns/nestjs-test-repo/pull/1#issue-298145583 hope it can help others to find a temporary solution.

**Comment by jedjebari** [comment]
I have the same kind of issue when putting a typescript file in my root dir (ie at the same level than src folder)
To fix that, I would say that you need to play with rootDir and include options in your tsconfig files.

But at the end, I guess you might want to build your artifacts in separate folders : dist/libs/utils and dist/website. I mean that you will want to replace src by something else. So you might put your folders libs/utils and website under a src folder

@kamilmysliwiec  : I understand that library is not fully supported, but if you agree I would be happy to submit a PR to update the current tsconfig file with a rootDir (because it's so easy to add a ts file in rootDir, that's what I always do when I read the graphql doc with generate-typings.ts : https://docs.nestjs.com/graphql/quick-start)

**Comment by kamilmysliwiec** [comment]
@jedjebari PRs are always welcome!

**Comment by kamilmysliwiec** [comment]
This issue is addressed by the lastest changes to the CLI https://trilon.io/blog/announcing-nestjs-monorepos-and-new-commands
