### ISSUE TITLE
 ts.createIncrementalProgram is not a function

### ISSUE THREAD

**Issue by Themandunord** [nestjs/nest-cli#430]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Since the 6.11.0 release, when I do `nest buil`I have this error : `ts.createIncrementalProgram is not a function`

![image](https://user-images.githubusercontent.com/2819925/67620375-6fc22f00-f806-11e9-8622-3ab51da038e5.png)

When I do a yarn run build, it's working.

## Expected behavior

No error, and the build can start

## Minimal reproduction of the problem with instructions

6.11.0 release

## Environment

```
ALL
```

**Comment by SloCompTech** [comment]
Confirming the bug, got the same message:
```
Error  ts.createIncrementalProgram is not a function
```
If I downgrade to **6.10.5** it works, but 6.11 gives error

**Comment by kamilmysliwiec** [comment]
Fixed in 6.11.1. 

Note: since globally installed `@nestjs/cli` will use **globally** installed `typescript` package, I'd suggest updating `typescript` as well (if you want to leverage all the latest & greatest features/fixes they introduced). If you update global `typescript`, `@nestjs/cli@6.11.0` will work fine as well.
