### ISSUE TITLE
generate commands not working on windows

### ISSUE THREAD

**Issue by BioPhoton** [nestjs/nest-cli#56]
Problem:
I'm not able to run `nest g module test` on my windows machine. Neighter in the powershell nor in gitbash.

Error: 
`ENOENT: no such file or directory, mkdir 'C:\C:\C:'`

Version:
OS Version Windows 10
NodeJS Version v6.9.0 Boron
NPM Version 5.3.0
nestjs-cli 2.0.0-rc.3

THX for your time you spent on this repo and also nestjs!!

**Comment by ThomRick** [comment]
Hey @BioPhoton !

Thanks a lot for your feedbacks !
Your issue is already opened here #55

I ll won't fix this issue on this cli version because I'm currently integrating the angular schematics template engine ;-)
Angular team already solved these path issues so I'll use their great engineering work ;-)

So I'll close your issue but thanks again ;-)
