### ISSUE TITLE
npm run start:dev does not start express server

### ISSUE THREAD

**Issue by yousss** [nestjs/nest-cli#751]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Environment

```

```

**Comment by jmcdo29** [comment]
If you are facing an issue, please provide more information in your description. A minimum reproduction repository and system information would be great as well. Otherwise, please refrain from opening issues.

If you are looking for support, please use our [Discord](https://discord.gg/nestjs) as we are using GitHub to track Feature Requests and Bug Reports.
